project:
  type: website

website:
  title: "epinzur.github.io"
  cookie-consent: true
  google-analytics: "G-0TFWEQ26VG"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/epinzur
      - icon: linkedin
        href: https://www.linkedin.com/in/epinzur
format:
  html:
    theme: cosmo
    css: styles.css
