project:
  type: website

website:
  title: "Eric's Blog"
  cookie-consent: true
  google-analytics: "G-0TFWEQ26VG"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/epinzur
      - icon: linkedin
        href: https://www.linkedin.com/in/epinzur
  favicon: images/favicon.ico
  open-graph: true
  twitter-card: true
format:
  html:
    theme: cosmo
    css: styles.css
